name: Actions test
on:
  push:
    branches:
      - 'staging'
      - 'production'

jobs:
#  dump_contexts_to_log:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: Dump job context
#        env:
#          JOB_CONTEXT: ${{ toJson(job) }}
#        run: echo "$JOB_CONTEXT"
#      - name: Dump steps context
#        env:
#          STEPS_CONTEXT: ${{ toJson(steps) }}
#        run: echo "$STEPS_CONTEXT"
#      - name: Dump runner context
#        env:
#          RUNNER_CONTEXT: ${{ toJson(runner) }}
#        run: echo "$RUNNER_CONTEXT"
#      - name: Dump strategy context
#        env:
#          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
#        run: echo "$STRATEGY_CONTEXT"
#      - name: Dump matrix context
#        env:
#          MATRIX_CONTEXT: ${{ toJson(matrix) }}
#        run: echo "$MATRIX_CONTEXT"

  ## Wait for docker to start
  docker-init:
    runs-on: arc-runner-set
    steps:
      - name: docker-init
        run: until docker info 2>/dev/null; do sleep 1; done
  ## Build image
  build:
    if: github.ref_name == 'staging' || github.ref_name == 'production'
    needs: [docker-init]
    runs-on: arc-runner-set
    steps:
      - name: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            #{{ $DOCKER_DO_REGISTRY/github.event.repository.name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=raw,latest

      - uses: docker/setup-buildx-action@v3

      ## - login to docker
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_DO_REGISTRY }}
          username: ${{ secrets.DOCKER_DO_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_DO_REGISTRY_PASSWORD }}

      ## - pull the latest image for the current project
      ## - build the image for the current project
      ## - tag the newly created image as the current commit SHA and as latest
      ## - push the tags to the registry
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  ## Deploy staging
  deploy-staging:
    if: github.ref_name == 'staging'
    runs-on: arc-runner-set
    needs: [ build ]
    steps:
      ## login to docker
      ## pull the image with current commit SHA for the current project
      ## tag the image as staging
      ## push the staging tag

      - run: echo "deploy-staging"

  ## Deploy production
  deploy-production:
    if: github.ref_name == 'production'
    runs-on: arc-runner-set
    needs: [ build ]
    steps:
      ## login to docker
      ## pull the image with current commit SHA for the current project
      ## tag the image as production
      ## push the production tag
      - run: echo "deploy-production"